### ISSUE TITLE
Timer period warning with ReactNative

### ISSUE THREAD

**Issue by cwiejack** [pubnub/react#1]
Hi, 
using pubnub (4.13.0) and pubnub-react (1.0.1) together with react-native (0.47.1) I get 2 warnings:
> Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
08-07 09:37:24.096  5312  5350 W ReactNativeJS: (Saw setTimeout with duration 310000ms)

and
> Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
08-07 09:37:24.102  5312  5350 W ReactNativeJS: (Saw setInterval with duration 149000ms)

**Comment by laksh1010** [comment]
how you fixed it ? thanks

**Comment by cwiejack** [comment]
Hi,
havn't fixed it, just applied a workaround. We just ignored the warning with 
``console.ignoredYellowBox = ['Setting a timer']``

**Comment by mrozbarry** [comment]
Is there any status on this actually being a bug? This is probably not a great for mobile, since this may force an app to eat through battery-life.

I'd prefer if the accepted answer wasn't _just ignore it for now_.

**Comment by neilhamilton** [comment]
The only thing I was able to come up with to at least legitimately get rid of the two separate warnings was to pass these two parameters in the PubNub initialization. This does result in more requests happening which may come with other issues regarding battery life (haven't tested on real device) but it at least covers React Native's suggestions for timeout lengths.

`subscribeRequestTimeout: 50000,
presenceTimeout: 100`

Your constructor in your component may look like this for Android:

```
  constructor (props) {
    super(props)
    this.pubnub = new PubNubReact({ 
      publishKey: 'YOUR_PUB_KEY', 
      subscribeKey: 'YOUR_SUB_KEY',
      subscribeRequestTimeout: 50000, // send polling request every 50 seconds
      presenceTimeout: 100 // 100 seconds
    });
    this.pubnub.init(this);    
  }
```
`presenceTimeout` [is covered here](https://www.pubnub.com/docs/web-javascript/api-reference-configuration) while I had to dig `subscribeRequestTimeout` out of the code.

It looks like `presenceTimeout` is in seconds while `subscribeRequestTimeout` is in milliseconds.

**Comment by fcaride** [comment]
getting the same with the pubnub library v4

**Comment by fcaride** [comment]
No fixes yet??

**Comment by PuKoren** [comment]
I guess the proper way to "fix" this would be to use the PubNub java SDK and wrap it into a JavaScript module.

I'm building a demo app using pubnub so it will be ok, but I won't use it for the production release as it is.

 Is there any plans for this? If there is no plan, maybe we can help, but we would need an answer first

**Comment by PizzaBrandon** [comment]
Can someone from PubNub comment on this about whether this can be corrected or if RN users need to implement the above workaround?

**Comment by PizzaBrandon** [comment]
Linking to the associated RN issue: https://github.com/facebook/react-native/issues/12981

**Comment by pubnubcraig** [comment]
All - if you want prompt action, always report your issue to PubNub Support.

**Comment by raipubnub** [comment]
Setting the  subscribeRequestTimeout in milliseconds and the presenceTimeout in seconds to a lower value removed the warning in android emulator about setting timers for multiple minutes. Testing using Pixel XL emulator API 29. Checking to see if there are any any other issues with setting these timeout values.
```
    this.pubnub = new PubNubReact({
      ...
      subscribeRequestTimeout: 60000,
      presenceTimeout: 122,
    });
```

**Comment by ricardovf** [comment]
This is filling the console and making it hard to debug. Can you check the defaults for sane values that does not trigger warnings?

`````
Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setInterval with duration 149000ms)
- node_modules/expo/build/environment/logging.js:25:23 in warn
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:274:8 in setInterval
- node_modules/pubnub/lib/core/components/subscription_manager.js:327:41 in _registerHeartbeatTimer
- node_modules/pubnub/lib/core/components/subscription_manager.js:308:6 in reconnect
- node_modules/pubnub/lib/core/components/subscription_manager.js:206:6 in adaptSubscribeChange
* src/services/AuthenticatedSocket.ts:46:26 in startPubnub$
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:30 in invoke
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:135:28 in invoke
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:170:17 in <unknown>
- node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:23 in doResolve
- node_modules/promise/setimmediate/core.js:66:12 in Promise
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:169:27 in callInvokeWithMethodAndArg
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:192:38 in enqueue
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:216:8 in async
* null:null in startPubnub
`````

**Comment by raipubnub** [comment]
Did the settings above work for you? We’ll dig deeper to get better defaults in the next release.

**Comment by ricardovf** [comment]
> Did the settings above work for you? We’ll dig deeper to get better defaults in the next release.

I did not try because the default subscribeRequestTimeout is about 5 minutes, right? Im afraid to change the defaults as im starting to migrate our websockets to pubnub. Are this settings safe? We are using on devices that will be turned on and connected all day long running on kiosk mode.

**Comment by raipubnub** [comment]
The settings are safe, however, you would be sending more subscribe requests than the standard defaults. Another option is to use these settings only for development and testing and switch them back to the defaults when deploying to production since it is only a warning on android side and the functionality should not be impacted.

**Comment by ricardovf** [comment]
> The settings are safe, however, you would be sending more subscribe requests than the standard defaults. Another option is to use these settings only for development and testing and switch them back to the defaults when deploying to production since it is only a warning on android side and the functionality should not be impacted.

The warning desapear with that settings. So im using that settings only on DEV. Thanks

**Comment by are** [comment]
Just to summarize things for other folks:

1. When creating the PubNub client, use `subscribeRequestTimeout` and `presenceTimeout` settings to reduce the timings to [acceptable values](https://github.com/pubnub/react/issues/1#issuecomment-513331155).
2. You can ignore this specific warning ([React Native docs on how to do this](https://facebook.github.io/react-native/docs/debugging#warnings) and [why you might want to avoid doing that](https://github.com/facebook/react-native/issues/12981)).
