### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by nicholasrq** [pubnub/react#18]
Any plans on implementing TS types for pubnub-react? It's kinda pain for now to work with this lib using TS.

**Comment by dabakovich** [comment]
Any updates on this, guys?
Please, add pubnub client type at least. It will very simplify using of client's methods.

**Comment by nicholasrq** [comment]
@dabakovich looks like they'll be implementing TS in Pubnub React 2.0, at least i've found tsconfig file in the 2.0 branch

**Comment by dabakovich** [comment]
Yeah, but for example, here is a declaration of usePubNub hook:
`export declare function usePubNub(): any;`
And the same situation with other components of new react-native. So I need manually get types from 'pubnub' library.

**Comment by davidnub** [comment]
@nicholasrq @dabakovich Thanks for the feedback and comments. Apologies for the delayed response. We've been busy re-analyzing our SDKs with our new SDK Team. 

As you've noticed we've started a PubNub React 2.0 branch and have released it in npm as `beta`. Please use it and provide feedback as we hope to address developer pain points and improve upon our SDKs in general. 

We appreciate the feedback!

**Comment by davidnub** [comment]
Oh I also forgot to mention the meat of this issue, which was the Typescript typings. Thanks for pointing out the lack of them. It is true that our problem actually is rooted from the underlying JS SDK not having valid Typescript typings. 

We were planning on re-vamping the JS SDK as well at some point but in the interim I think having some sort of generated Typescript typings would be helpful for all. In other words, we're on it. 👍

**Comment by are** [comment]
v2.0 is written using TypeScript, and it uses the typings from DefinitelyTyped repository for PubNub client instance. Everything should be fine now - if you find that any typings are missing, please report that in the [Javascript PubNub SDK](https://github.com/pubnub/javascript/issues)!
