### ISSUE TITLE
Npm 4 High severity vulnerabilities

### ISSUE THREAD

**Issue by MiguelArmendariz** [pubnub/react#36]
Greetings,

I just installed the package but it gave the warning written on the title.

PATH:  pubnub-react => pubnub => superagent-proxy => proxy-agent => pac-proxy-agent => https-proxy-agent

NPM Advisory: https://npmjs.com/advisories/1184 

But my question is, is it safe to proceed using the react sdk of pubnub?

**Comment by davidnub** [comment]
Hi @MiguelArmendariz,

Thanks for your interest in PubNub's SDKs. We're aware of the vulnerabilities and are in the progress of rectifying some of these issues alongside adding more features! The current recommended path would be to use the `beta` versions of both of our React and JS SDKs.

React SDK v2.0 beta https://github.com/pubnub/react/tree/v2.0
JS SDK v4.30.0-beta.0 https://www.npmjs.com/package/pubnub/v/4.30.0-beta.0

I hope that works for you while we're cleaning things up.

**Comment by MiguelArmendariz** [comment]
@davidnub I've reviewed the 1.0 and the beta from the react pubnub. It seems kinda odd to use.
I will still try it due to having an issue when trying to implement the JS SDK.

I can't seem to fetch the new messages from the listener, it might work having the pubnub stuff inside the component, but I want to use a separate file from it like when using the angular js sdk.

Thanks tho. I think you can close this ticket

**Comment by davidnub** [comment]
Sounds good. 

Thanks for the feedback @MiguelArmendariz . We appreciate all the suggestions we can get. Feel free to contact Support for further assistance if you'd like more hands on help.
