### ISSUE TITLE
useState vs useReducer

### ISSUE THREAD

**Issue by AshesOfOwls** [pubnub/react#37]
Hiya,

I ran into an issue with the example provided in the readme. useState seems to always call the useEffect hook when setting the array of messages, therefore resubscribing on every render that the messages change.

To fix this we used useReducer to remove the state from the component and it fixed the issue. Should this be used going forward?

**Comment by MessagingMoore** [comment]
Hi @AshesOfOwls, Thank you so much for pointing this out.  We're looking into how to respond.  Thanks for your patience.

**Comment by are** [comment]
Hi @AshesOfOwls, thanks for your patience! This is the same issue as #43, both are solved now. The issue stems from using Consumer not wrapped in the memo. Check the v2.0 branch for an updated example!
