### ISSUE TITLE
Example code problems

### ISSUE THREAD

**Issue by vikramkh** [pubnub/react#43]
So I'm using pubnub v2, and the code is pretty much the same as the example code, except every time the component renders, the client.addListener code gets run, so it keeps adding listeners and subscribing to the channels. How can I remove the client away from the render portion?

**Comment by are** [comment]
Hi @vikramkh! This is an issue that is inherent to using (any) Consumers with children render function. I will update the example to use the `usePubNub` and `useEffect` hook to prevent multiple subscriptions and I'll let you know when its done so you can check it out!

**Comment by are** [comment]
You can see the updated example on the v2.0 branch.
