### ISSUE TITLE
Store does not have a valid reducer. react-native

### ISSUE THREAD

**Issue by RamashishTomar** [pubnub/react#49]
I have been trying to integrate pubnub on a react-native application using redux. the official documentation is too much buggy  and not complete for a new user. 

here is my code  whic is according to the [official documentation](https://www.pubnub.com/docs/chat/redux/using)

below is my code 
`import { combineReducers } from 'redux';`
`import PubNub from 'pubnub';`
`import {
    createNetworkStatusReducer,
    createMessageReducer,
    createPresenceReducer,
    createUserReducer,
    createSpaceReducer,
    createMembershipReducer,
    createMembersReducer,
    createPubNubListener,
} from 'pubnub-redux';`
`import { createStore, applyMiddleware } from 'redux';
import ReduxThunk from 'redux-thunk';
import ChatReducer from './ChatReducer'`
`const pubnub = new PubNub({
    subscribeKey: "sub-c*****",
    publishKey: "pub-c*****",
    uuid: "0"
});`
`export let rootReducer = combineReducers(
    createNetworkStatusReducer,
    createMessageReducer(),
    createPresenceReducer(),
    createUserReducer(),
    createSpaceReducer(),
    createMembershipReducer(),
    createMembersReducer()
);`

`let thunkArgument = {
    pubnub: {
        api: pubnub
    }
};`

`export let middleware = applyMiddleware(ReduxThunk.withExtraArgument(thunkArgument));`

`export let store = createStore(
  rootReducer,
  middleware,
);`

its giving me : 
> Store does not have a valid reducer. Make sure the argument passed to combineReducers is an object whose values are reducers.

**Comment by MessagingMoore** [comment]
Hi @RamashishTomar, I notice this line in the code you posted:
```
export let rootReducer = combineReducers( createNetworkStatusReducer, createMessageReducer(), createPresenceReducer(), createUserReducer(), createSpaceReducer(), createMembershipReducer(), createMembersReducer() );
```

When the code references `createNetworkStatusReducer` it is passing the function which creates the reducer, not the reducer.  Does calling `createNetworkStatusReducer()` solve the problem?

**Comment by pzprado** [comment]
I'm having the same issue - tried your suggestion to no success @MessagingMoore, plus the ```createNetworkStatusReducer()``` requires a boolean value, if empty this is the error:
```Uncaught Error: The initializer parameter must be a boolean value (true or false) or function```

For the other reducers, I tried with ```true``` or ```false``` values, empty, one reducer or many, still getting the message described in the issue ("Store does not have a valid reducer...")

**Comment by MessagingMoore** [comment]
Sorry, I missed the greater problem in my earlier response.  `CombineReducers` requires an object as a parameter, not each reducer as a parameter.  See an example of usage here:
https://redux.js.org/api/combinereducers#combinereducersreducers
