### ISSUE TITLE
React Native Push Notifications documentation issue

### ISSUE THREAD

**Issue by erikfenriz** [pubnub/react#52]
Hello, PubNub team!
My team wants to use PubNub to implement it in our project.
I've been following this documentation to set it up in React Native application:
https://www.pubnub.com/blog/react-native-push-notifications-ios-android/

The issue is that I get the error when I use the code from the example:
```
this.pubnub = new PubNubReact({
        publishKey: 'YOUR_PUBNUB_PUBLISH_KEY_HERE',
        subscribeKey: 'YOUR_PUBNUB_SUBSCRIBE_KEY_HERE'
    });
    this.pubnub.init(this);
```
**TypeError Object is not a constructor (evaluating new_pubnubReact.default')**

It seems that the documentation is outdated.
My main goal right now is to make it work with remote push notifications for iOS and Android.
What would be the correct way to do this?
I would love to get a code example that would cover my issue.

I want PubNub to work along with react-native-push-notification library, so I am using it in the NotificationManager class like so: 

```
class NotificationManager {
  constructor() {
    this.pubnub = new PubNubReact({
        publishKey: '--',
        subscribeKey: '--'
    });
    this.pubnub.init(this);
    PushNotification.configure({
      onRegister: function(token) {
          console.log( 'TOKEN:', token );
          if (token.os == "ios") {
            this.pubnub.push.addChannels(
            {
              channels: ['notifications'],
              device: token.token,
              pushGateway: 'apns'
            });
            // Send iOS Notification from debug console: {"pn_apns":{"aps":{"alert":"Hello World."}}}
          } else if (token.os == "android"){
            this.pubnub.push.addChannels(
            {
              channels: ['notifications'],
              device: token.token,
              pushGateway: 'gcm' // apns, gcm, mpns
            });
            // Send Android Notification from debug console: {"pn_gcm":{"data":{"message":"Hello World."}}}
          }  
      }.bind(this),
...

```

Versions:
"pubnub": "^4.27.5",
"pubnub-react": "^2.0.0",
"react": "16.9.0",
"react-native": "0.61.5",

**Comment by MessagingMoore** [comment]
Hi.  

The Blog post you linked to is using the 1.0 version of the React library, which re-exported the interface of the underlying PubNub Javascript SDK.  

in your example if instead of `this.pubnub = new PubNubReact(` try `this.pubnub = new PubNub(` and `import PubNub from "pubnub".  The interface should work as described in the blog.

The current 2.0 of the react implementation can be used to provide and consume this instance of the PubNub SDK via the React Context interface as described here: https://www.pubnub.com/docs/chat/react/setup
