### ISSUE TITLE
Invariant Violation: update(): $merge expects a target of type 'object'; got undefined

### ISSUE THREAD

**Issue by yokesharun** [pubnub/react#7]
Error : Invariant Violation: update(): $merge expects a target of type 'object'; got undefined

pubnub-react :  ^1.0.2
react : 16.0.0-beta.5
react-native : 0.49.3

i followed this documentation : [https://www.npmjs.com/package/pubnub-react](https://www.npmjs.com/package/pubnub-react)

i got error when i use this line **this.pubnub.init(this);**  so i remove this line. now i can able to send the message but i cant listen.

**Comment by ManuelFernando** [comment]
@yokesharun According to the version 16.0.0 we had to introduce some changes on documentation. The documentation here will update this week. You can use this https://www.pubnub.com/docs/react-native-javascript/pubnub-javascript-sdk

**Comment by ManuelFernando** [comment]
@yokesharun I just saw and the doc here and NPM are updated, please let me know if this works for you?

**Comment by yokesharun** [comment]
@ManuelFernando now i can able to send the messages to particular channel and followed [https://www.pubnub.com/docs/react-native-javascript/pubnub-javascript-sdk#get-message](https://www.pubnub.com/docs/react-native-javascript/pubnub-javascript-sdk#get-message) this doc for receiving real time message which is emitted from other end is not working.

**Comment by ManuelFernando** [comment]
@yokesharun I don’t know if I could understand you very well, you’re trying to tell me when from other client is published a message, this message doesn’t arrive to your react app

**Comment by yokesharun** [comment]
**Are you using the same keys for both applications?**
Yes
**The same channel?**
Yes
**Are you receiving any errors?**
No
**Is it the react native code not receiving messages?**
Yes


i'm using pubnub for chat application. 
User A is using an Android Application called Sender. 
User B is using React Native iOS Application Called Receiver. 

User B can able to send messages to User A. (i.e ) from react native iOS to android
But
User B can't able to receive any of the messages from User A. (i.e ) from android  to react native iOS 

NOTE : When USER A and USER B uses the same Android application means the chat works fine.

Actually i have used PUBNUB DEBUGGER CONSOLE : https://www.pubnub.com/docs/console

**QUESTION :**

I need to Know which function i need to use in react native to get the real time messages from the channel?

**Comment by ManuelFernando** [comment]
Can you share some piece of code where can I see how you’re initializing the sdk

**Comment by yokesharun** [comment]
```
import PubNubReact from 'pubnub-react';

export default class ChatComponent extends Component {
    constructor(props) {
        super(props);

        this.pubnub = new PubNubReact({
            publishKey: Constants.PUBNUB_PUB,
            subscribeKey: Constants.PUBNUB_SUB
        });

        this.pubnub.init(this);
    }

    componentDidMount() {

        this.pubnub.subscribe({
            channels: ['channel_7']
        });

        this.pubnub.getMessage('channel_7');
    }

    componentWillUnmount(){
        this.pubnub.unsubscribe({
            channels: ['channel_7']
        });
    }

    sendMessage() {
        var publishConfig = {
            channel : 'channel_7',
            message : "Hello"
        }

        this.pubnub.publish(publishConfig);
    }
}

```
I need to know how to get the real time messages from channel_7?

**Comment by ManuelFernando** [comment]
@yokesharun I couldn’t the method render

**Comment by yokesharun** [comment]
@ManuelFernando i have in my source code. i just pasted the functionality code here for your understanding

**Comment by ManuelFernando** [comment]
@yokesharun but in this code I can’t see the implementation of the method render()

**Comment by yokesharun** [comment]
the rendering function 
```
  renderItem({item}) {
        return (
          <View style={styles.row}>
            <Image style={styles.avatar} />
            <View style={styles.rowText}>
              <Text style={styles.sender}>You</Text>
              <Text style={styles.message}>{item.message}</Text>
            </View>
          </View>
        );
    }

  render() {
      const messages = this.pubnub.getMessage('channel_7');
    return (

       <FlatList
          inverted
          style={styles.BottomLayout}
          data={messages}
          renderItem={this.renderItem}
          keyExtractor={(item, index) => item.id}
        />
    );
  }

```

**Comment by ManuelFernando** [comment]
@yokesharun can you replace componentDidMount to componentWillMount; componentWillMount will acts before the first render then will do the process of subscription first. I think this will resolve your trouble.

**Comment by ManuelFernando** [comment]
@yokesharun was your issue resolved?

**Comment by yokesharun** [comment]
@ManuelFernando still its not working. i have changed as you said. can you give me some working example it will be great

```
import PubNubReact from 'pubnub-react';

export default class ChatComponent extends Component {
    constructor(props) {
        super(props);

        this.pubnub = new PubNubReact({
            publishKey: Constants.PUBNUB_PUB,
            subscribeKey: Constants.PUBNUB_SUB
        });

        this.pubnub.init(this);
    }

    componentWillMount() {

        this.pubnub.addListener({
            status: st => {
                if (st.category === "PNUnknownCategory") {
                    var newState = { new: "error" };
                    pubnub.setState(
                        {
                            state: newState
                        },
                        function(status) {
                            console.log(st.errorData.message);
                        }
                    );
                }
            },
            message: message => {
                console.log(message);
            }
        });

        this.pubnub.subscribe({
            channels: ['channel_7']
        });

    }

    componentWillUnmount(){
        this.pubnub.unsubscribe({
            channels: ['channel_7']
        });
    }

    sendMessage() {
        var publishConfig = {
            channel : 'channel_7',
            message : "Hello"
        }

        this.pubnub.publish(publishConfig);
    }

        renderItem({item}) {
            return (
              <View style={styles.row}>
                <Image style={styles.avatar} />
                <View style={styles.rowText}>
                  <Text style={styles.sender}>You</Text>
                  <Text style={styles.message}>{item.message}</Text>
                </View>
              </View>
            );
        }

      render() {
          const messages = this.pubnub.getMessage('channel_7');
        return (

           <FlatList
              inverted
              style={styles.BottomLayout}
              data={messages}
              renderItem={this.renderItem}
              keyExtractor={(item, index) => item.id}
            />
        );
      }
}
```

**Comment by ManuelFernando** [comment]
@yokesharun 
`import React, { Component } from 'react';
import PubNubReact from 'pubnub-react';

export default class extends Component {
  constructor(props) {
    super(props);
    this.pubnub = new PubNubReact({ publishKey: 'YOUR PUBLISH KEY', subscribeKey: 'YOUR SUBSCRIBE KEY' });
    this.pubnub.init(this);
  }
  
  componentWillMount() {
    this.pubnub.subscribe({ channels: ['channel1'], withPresence: true });
    
    this.pubnub.getMessage('channel1', (msg) => {
      console.log(msg);
    });
    
    this.pubnub.getStatus((st) => {
      console.log(st);
      this.pubnub.publish({ message: 'hello world from react', channel: 'channel1' });
    });
  }
  
  componentWillUnmount() {
    this.pubnub.unsubscribe({ channels: ['channel1'] });
  }
  
  render() {
    const messages = this.pubnub.getMessage('channel1');
  return (
    <div>
      <ul>
        {messages.map((m, index) => <li key={'message' + index}>{m.message}</li>)}
      </ul>
    </div>
  );
  }
}`

If you see componentWillMount, in this point the sdk subscribes the channel and start to listening all real time messages when is executed getMessage. When getMessage is executed inside of render() this is used to display the messages in the UI. If you add a listener you have to manage all flow to the render for yourself.  You can see all examples in the section: Trigger Event
