### ISSUE TITLE
Plans to reduce the bundle size?

### ISSUE THREAD

**Issue by sidharth-ping** [pubnub/react#74]
Hey do you have any plans to reduce the bundle size? 

Right now the packages measures 240 kb total which is slowing down my website.

**Comment by puopg** [comment]
Yea no kidding, even gzipped this is 52 KB.

**Comment by are** [comment]
This is mostly because of the PubNub JavaScript SDK - React wrapper itself is pretty small. We do plan to migrate the JavaScript SDK towards more modular, tree-shakeable architecture in near future. Thanks for your patience!
